- .gitignore
/kind chore
Ignore the terraform lock file by changing .terraform to .terraform*
Closes #
> chore: ignore terraform lock file

- deploy/systemd/open-saves-gc.service
- deploy/systemd/open-saves-gc.timer
- docs/deploying.md
/kind docs
It adds a new section to the deployment guide to run the garbage collector automatically.
Closes #202 
> docs: Add garbage collector instructions

- README.md
/kind docs
Update the README with overview and links to each document.
Closes #
> docs: update README with overview and links

- README.md
> docs: add link to overview and fix link on README

- docs/development.md
> docs: fix broken link

- README.md
Add simple badges: pkg docs, goreport, license, release
> docs: add github badge to readme

- README.md
- go.mod
- go.sum
- internal/app/collector/collector.go
- internal/pkg/blob/gcs.go
- internal/pkg/cache/cache.go
- internal/pkg/cache/redis.go
- internal/pkg/cache/redis_test.go
- internal/pkg/metadb/blob.go
- internal/pkg/metadb/datastore/cursor.go
- internal/pkg/metadb/datastore/datastore_test.go
- internal/pkg/metadb/record.go
> /kind style
Fixes various reported styling errors from golint/goreport (ineffectual assignments, documentation on exported fields, error strings should not be capitalized)
> style: fix reported errors from goreport/other linters

- docs/deploying.md
> docs: update TOC in deployment guide

- deploy/gke/deployment.yaml
- deploy/gke/service.yaml
/kind chore
Add license to gke yaml files.
Closes #
> chore: add license to gke yaml files

- internal/pkg/metadb/timestamps/uuid_test.go
/kind test
Add tests for timestamps.uuid functions as they became public functions.
Closes #236 
> test: add tests for timestamps.uuid functions

- internal/pkg/metadb/blobref/blobref.go
- internal/pkg/metadb/metadb.go
- internal/pkg/metadb/metadb_test.go
- internal/pkg/metadb/timestamps/timestamps.go
- internal/pkg/metadb/timestamps/timestamps_test.go
/kind refactor
The timestamps package should own and manage precisions for consistency.
Closes #247 
> refactor: timestamps pkg owns precision

- internal/app/server/open_saves.go
- internal/pkg/metadb/record/record.go
- internal/pkg/metadb/record/record_test.go
- internal/pkg/metadb/store/store.go
- internal/pkg/metadb/store/store_test.go
/kind refactor
Renames New{Store,Record}FromProto to FromProto for consistency and conciseness as they are in separate packages now.
Closes #
> refactor: rename New{Store,Record}FromProto to FromProto

- internal/app/collector/collector.go
- internal/app/server/open_saves.go
- internal/pkg/cache/redis/redis.go
- internal/pkg/cache/redis/redis_test.go
/kind refactor
Give redis code its own package so to enforce encapsulation.
Closes #
> refactor: redis code has its own package

- internal/app/collector/collector.go
/kind fix
collector ran into an infinite loop when the iterator returned error. This patch fixes the issue.
Closes #204 
> fix: collector runs into infinite loop

- internal/app/collector/collector.go
- internal/app/collector/collector_test.go
/kind fix
When you run collector, it skipped blobref entries when the blob storage returns errors, but it should delete when the error was NotFound. This PR fixes the issue. Collector deletes BlobRef entries when the associated objects are not found.
Closes #205 
> fix: collector removes BlobRefs when blob is not found

- Makefile
- internal/app/collector/collector.go
- internal/app/server/open_saves.go
- internal/app/server/open_saves_test.go
- internal/pkg/cache/cache.go
- internal/pkg/cache/cache_test.go
- internal/pkg/cache/redis_test.go
- internal/pkg/metadb/record/record.go
- internal/pkg/metadb/record/record_test.go
/kind refactor
Introduce a new Cacheable interface and make encoding and decoding a responsibility of each package (such as Record).
This patch also changes Cache to a struct and moved some encoding and decoding codes into the class. This will make it easier to support caching for additional classes.
Closes #
> refactor: Introduce Cacheable interface

- internal/pkg/metadb/blobref/chunkref/chunkref.go
- internal/pkg/metadb/blobref/chunkref/chunkref_test.go
/kind feat
Add a new struct ChunkRef to manage chunked blob objects. Server implementations will be added later.
Closes #
> feat: Add ChunkRef struct

- internal/pkg/metadb/blobref/blobref.go
- internal/pkg/metadb/blobref/blobref_test.go
- internal/pkg/metadb/blobref/chunkref/chunkref.go
- internal/pkg/metadb/blobref/chunkref/chunkref_test.go
- internal/pkg/metadb/metadb.go
- internal/pkg/metadb/metadb_test.go
- internal/pkg/metadb/metadbtest/metadbtest.go
- internal/pkg/metadb/metadbtest/metadbtest_test.go
/kind feat
This PR adds metadata operations necessary to implement chunked blobs.
Closes #
The server implementation will be submitted as another PR.
> feat: Metadata operations for chunked blobs

- docs/reference.md
/kind docs
Updates reference API for chunked uploads
> docs: update API reference

- docs/deploying.md
/kind docs
A few more prereqs are required to run the tutorial smoothly 
-Go needs to be installed at beginning, so a terminal restart during installation doesn't erase all the env variables
-Service account referenced in garbage collector section needs to be created earlier
-Need to emphasize that there's a choice between Cloud Run & GKE
Haven't made it through the garbage collection section yet, but more instructions may be required for docker installation.
> docs: Add prerequisites to deployment guide

- cloudbuild_update_images.yaml
/kind fix
Updates to the main branch failed in Cloud Build. Add the proper tag from substitution var to build and tag properly.
> fix: add proper build tag

- docs/deploying.md
/kind docs
Add a missing backslash
Closes #
> docs: Add a missing backslash in deploying.md

- go.mod
- go.sum
- internal/pkg/metadb/blobref/chunkref/chunkref.go
- internal/pkg/metadb/blobref/chunkref/chunkref_test.go
- internal/pkg/metadb/record/record.go
/kind refactor
Replaces gob encoding with msgpack, which is more efficient
Closes #277
> refactor(pubsub): replace gob with msgpack

- README.md
/kind docs
change alpha to beta in readme to reflect the current status.
Closes #
> docs: change alpha to beta in readme

- deploy/datastore/index.yaml
- docs/deploying.md
/kind docs
As per troubleshooting session with yuryu, a couple tweaks are needed for the garbage collection section.
-Adding Datastore index.yaml
-Fix docker run command
N/A
> docs: Tweaking steps for garbage collection

- Dockerfile
- scripts/open_saves_builder_base.Dockerfile
/kind chore
Update Go for the release and testing images to 1.17.
Closes #295 
> chore: update Go to 1.17

- internal/app/server/open_saves_test.go
/kind test
Refactor the code and remove duplicates.
Closes #298 
> test: use setupTestRecord more

- examples/grpc-client/main.go
- internal/app/collector/collector_test.go
- internal/app/server/open_saves_test.go
- internal/pkg/metadb/metadb_test.go
/kind refactor
Replace uuid.New().String() with uuid.NewString().
Closes #299 
> refactor: prefer uuid.NewString()

- docs/development.md
/kind docs
Remove notes on bazel and gazelle as they are not used anymore in development.
Closes #
> docs: remove notes on bazel/gazelle

- go.mod
- go.sum
- internal/app/server/open_saves_test.go
- internal/pkg/cache/redis/redis_test.go
- scripts/open_saves_builder_base.Dockerfile
- scripts/run_open_saves_test.sh
/kind test
Use miniredis in unit tests to remove dependency to the full Redis server.
Closes #348 
> test: use miniredis in unit tests

- internal/app/server/open_saves_test.go
- internal/pkg/config/loader.go
- internal/pkg/config/model.go
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
/kind refactor
ServerConfig.Cache is not used anymore.
Closes #349
> refactor: remove ServerConfig.Cache

- Dockerfile
/kind build
Fix a case where Dockerfile had wrong image name and the image builds were failing.
Closes #
> build: fix image builds in Dockerfile

- internal/app/collector/collector.go
- internal/app/server/open_saves.go
- internal/app/server/open_saves_test.go
- internal/pkg/blob/gcs.go
- internal/pkg/blob/gcs_test.go
/kind fix
NewBlobGCP used a new background context but it should instead
use a context passed from a caller.
Closes #
> fix(blob): pass base context in NewBlobGCP

- Makefile
/kind fix
Fixes a typo in the Makefile that was preventing proper cleanup
> fix: proper clean go proto in Makefile

- internal/pkg/blob/gcs_test.go
/kind test
Migrate from testify to go-cmp
Use tables for test cases
Closes #
> test(blob): testify -> go-cmp, use table

- configs/service.yaml
/kind chore
Fix variable name in config file
Closes #430
> chore: rename config variable to align with implementation
