internal/pkg/cache/redis_test.go
> /kind fix
Adds a flushall before running Redis test so it's not dependent on
being empty prior to running the test
Closes #190
=> fix: remove redis test's empty database prerequisite

internal/app/collector/collector_test.go, internal/pkg/metadb/metadb.go, internal/pkg/metadb/metadb_test.go
/kind refactor
Replace grpc.Code and grpc.Errorf with status.Code and status.Errorf respectively because the functions in the grpc namespace have been deprecated and replaced by those in the status namespace.
Closes #226 
=> refactor: replace grpc.* error funcs with status.*

internal/app/collector/collector.go, internal/pkg/metadb/blobref/blobref.go, internal/pkg/metadb/blobref/blobref_test.go, internal/pkg/metadb/metadb.go, internal/pkg/metadb/metadb_test.go, internal/pkg/metadb/metadbtest/metadbtest_test.go
/kind refactor
Rename BlobRefStatus to Status to make it less redundant as it is now in a separate package. BlobRefStatus* constants are also changed to Status*.
Closes #
=> refactor: rename BlobRefStatus to Status

internal/pkg/metadb/blobref/blobref.go, internal/pkg/metadb/metadb.go, internal/pkg/metadb/metadb_test.go, internal/pkg/metadb/timestamps/timestamps.go, internal/pkg/metadb/timestamps/timestamps_test.go
/kind refactor
- Make timestamps.New a standalone function to avoid create and modify
- Rename NewTimestamps and UpdateTimestamps to New and Update to remove redundancy
Closes #246 
=> refactor: timestamps.New is now standalone

internal/app/server/open_saves.go
/kind fix
This fixes a bug where the server program allocates a buffer for an entire blob object, instead of a streaming message.
Closes #
=> fix: server allocated buffer for entire blob size

examples/grpc-client/main.go
/kind docs
Currently, the example does not work properly if `GOOGLE_APPLICATION_CREDENTIALS` is set. With the new `authenticate` flag, we dial the gRPC connection without authentication.
=> samples: update grpc example to support no authentication

internal/app/server/open_saves.go, internal/app/server/open_saves_test.go
/kind feat
Remove the arbitrary opaque string limit check and allow bigger strings. Still limited by the Datastore entity size limit.
Closes #279 
=> feat: remove opaque string limit check

internal/app/server/open_saves.go, internal/app/server/open_saves_test.go
/kind fix
Fix a crash bug when an invalid parameter was passed to CreateChunkedBlob.
Closes #281 
Proper tests will be added later but want to fix this crash bug first.
=> fix: crash in CreateChunkedBlob with invalid param

internal/app/server/open_saves.go, internal/app/server/open_saves_test.go, internal/pkg/metadb/blobref/blobref.go, internal/pkg/metadb/blobref/blobref_test.go, internal/pkg/metadb/blobref/chunkref/chunkref.go, internal/pkg/metadb/blobref/chunkref/chunkref_test.go, internal/pkg/metadb/metadb.go, internal/pkg/metadb/metadb_test.go, internal/pkg/metadb/metadbtest/metadbtest.go, internal/pkg/metadb/metadbtest/metadbtest_test.go, internal/pkg/metadb/record/record.go, internal/pkg/metadb/record/record_test.go
/kind feat
This PR implements the checksum support with CRC32C and MD5.
Closes #292 
=> feat: support CRC32C and MD5 checksums

internal/pkg/metadb/checksums/checksums.go
/kind fix
Fix wrong CRC32C error messages currently returning the received proto value
=> fix: wrong CRC32C checksums error message

internal/pkg/cache/redis/redis.go
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
/kind fix
When the redis connection retrieved form the pool is invalid, retry the operation (up to three times).
When this error happens, the redis cache becomes stales and does not have the latest data. This cause issues when performing PUT/PATCH operation since the signature read from Redis is stale.
Closes #323
https://gosamples.dev/broken-pipe/#:~:text=Share%3A,connection%20should%20be%20terminated%20immediately.
=> fix: retry redis operation on broken pipe error

go.mod, go.sum
/kind chore
Bump up go version to 1.17 in go.mod
We are already building the server and collector with go 1.17
Closes #326
=> chore: bump up go to 1.17 in mod file

deploy/datastore/index.yaml, deploy/terraform/gcp/datastore.tf, internal/app/server/open_saves_test.go, internal/pkg/metadb/metadb.go
/kind feat
Adds remaining support for inequality filters `<, >, <=, >=`. What this doesn't do is automatically create the datastore index required to support these. If these indexes are not created, `QueryRecords` will return an appropriate error from Datastore.
Closes #336
=> feat: add support for inequality filters

internal/app/server/open_saves.go, internal/app/server/open_saves_test.go
/kind fix
Fix a bug where UpdateRecord destroys a blob attached to the record.
Closes #305
=> fix: UpdateRecord destroys blob

configs/service.yaml, internal/app/server/open_saves.go, internal/pkg/config/loader.go, internal/pkg/config/model.go
/kind feat
This change allows users to configure blob size that is used to determine whether inline blob or external blob is used through the configuration file.
Closes #374
=> feat: make max inline blob size configurable

Dockerfile
/kind feat
Bundles the statically compiled [grpc_health_probe](https://github.com/grpc-ecosystem/grpc-health-probe) in the container image.
Closes #386
=> feat: bundle grpc_health_probe in image

internal/app/server/server.go
/kind fix
Adding `srv.GracefulStop` closes the listeners and the defer statement closing these listeners is erroneous and generates errors.
=> fix: remove defer statement closing listeners

internal/pkg/metadb/blobref/blobref.go, internal/pkg/metadb/record/record.go, internal/pkg/metadb/record/record_test.go
What type of PR is this?
/kind fix
What this PR does / Why we need it:
This PR maps a legacy field called "NumberOfChunks" to the newly named "ChunkCount" field. This change was implemented against the record and blobref so that all downstream functions are able to reference "ChunkCount" without there being any naming conflict. 
Which issue(s) this PR fixes:  Backward compatibility issue with Record created with NumberOfChunks #391
https://github.com/googleforgames/open-saves/issues/391
Special notes for your reviewer:
=> fix: backward compatibility with numberofchunks

internal/pkg/metadb/timestamps/timestamps_test.go, internal/pkg/metadb/timestamps/uuid_test.go
/kind test
This PR changes the timestamps tests to use go-cmp instead of tesitfy. Also rerrange tests to use table test cases.
Closes #
=> test(timestamps): testify -> go-cmp, use table

configs/service.yaml, go.mod, go.sum, internal/app/server/open_saves.go, internal/app/server/open_saves_test.go, internal/pkg/config/loader.go, internal/pkg/config/model.go
> /kind feat
Enables the default tracing provided by the Datastore client library, exporting to Cloud Trace. This allows us to view spans created by the Datastore client for transactions, viewing latency and some error metrics.
This change is EXPERIMENTAL and subject to change or removal without notice.
=> feat: enable opencensus tracing with cloud trace for datastore

internal/app/collector/collector_test.go, internal/app/server/open_saves.go, internal/app/server/open_saves_test.go, internal/pkg/metadb/metadb.go, internal/pkg/metadb/metadb_test.go
/kind fix
During chunk upload, open saves is doing multiple write operations on the same chunk entity. We have removed one write to follow best practices for Datastore and reduce database contention.
Closes #403 
=> fix: remove extra writes when uploading chunked data

configs/service.yaml, internal/app/server/server.go, internal/pkg/config/loader.go, internal/pkg/config/model.go
/kind fix
Add possibility to configure server keep alive parameters.
Closes #415 
=> feat: add configurations for keep alive on grpc server

configs/service.yaml, internal/app/server/server.go, internal/pkg/config/loader.go, internal/pkg/config/model.go, internal/pkg/tracing/tracing.go
=> feat: tracing propagation and service name prioritize envvar

configs/service.yaml, internal/app/server/open_saves_test.go, internal/pkg/cache/redis/redis.go, internal/pkg/config/loader.go, internal/pkg/config/model.go
=> feat: expose new redis config

Dockerfile, cloudbuild.yaml, go.mod
/kind chore
Addresses vulnerabilities that are fixed in go 1.20
Stable versions of go are the last two minor versions, go 1.20 and 1.21 
=> chore: bump minimum go version to 1.20

docs/contributing.md, internal/app/server/open_saves.go, internal/app/server/open_saves_test.go, internal/pkg/metadb/store/store.go, internal/pkg/metadb/store/store_test.go
/kind feat
This PR enables store caching.
Closes #404 
Since I'm not able to run the full test scenario in the gcp project I'm relying on the CI or someone to manually run it
=> feat: implement store caching

docs/overview.md, go.mod, go.sum, internal/pkg/cache/redis/redis.go, internal/pkg/cache/redis/redis_test.go, internal/pkg/config/model.go
chore: Increase the version of Redis Go client to v9 to have support for Redis v7.
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind fix
> /kind build
> /kind chore
> /kind ci
> /kind docs
> /kind style
> /kind refactor
> /kind perf
> /kind test
/kind feat
Adds support to Redis Cluster while keeping support for Redis Server (Single instance).
It replaces the basic Redis Client by the Universal Redis Client, which accepts multiple Redis IPs to allow Cluster behavior.
To keep full support with the previous version, the multiple addresses can be supplied via the same configuration property as a list of IP/addresses separated by commas (,) …
=> feat: Add support for Redis Cluster while keeping support for Redis Server

cmd/collector/main.go, configs/service.yaml, internal/app/collector/collector.go, internal/app/collector/collector_test.go, internal/pkg/cache/redis/redis.go, internal/pkg/cache/redis/redis_test.go, internal/pkg/config/loader.go, internal/pkg/config/model.go
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind feat
> /kind build
> /kind chore
> /kind ci
> /kind docs
> /kind style
> /kind refactor
> /kind perf
> /kind test
/kind fix
When testing Redis connection with GCP managed Redis Cluster we've seen that GCP expects clients to connect using a single discovery IP instead of the set of IPs that is expected by Go-Redis UniversalClient.
Closes #449
=> fix: Change Redis.go to support explicitely connecting to a Redis Cluster with a single address for GCP compatibility

Dockerfile, cloudbuild.yaml
/kind chore
Bump Golang version to 1.23 for open-saves-builder. 
https://github.com/googleforgames/open-saves/pull/461#issuecomment-2736721923
=> feat: Bump up Golang version to 1.23

cmd/collector/async/main.go, cmd/collector/main.go, configs/service.yaml, internal/app/collector/async/collector.go, internal/app/collector/collector.go, internal/pkg/config/loader.go, internal/pkg/config/model.go, internal/pkg/metadb/metadb.go, internal/pkg/metadb/metadb_test.go
Rename datastore_tx_max_retries to datastore_tx_max_attempts to better signal the usage of the property
/kind fix
Changes the name of the datastore_tx_max_retries config to datastore_tx_max_attempts as in Datastore code we don't set the number of retries (number of times the code will be attempted after the first one) but the total number of attempts.
Closes #471
=> fix: Rename datastore_tx_max_retries to datastore_tx_max_attempts
